add_metadata:
  unique_id: "unique_id"
  metrics_group_id: "metrics_group_id"
  metrics_baseline_control: "metrics_baseline_control"
  batch_run_id: "batch_run_id"
  batch_sample_id: "batch_sample_id"
  batch_sample_modal_repeat: "batch_sample_modal_repeat"

find_ladders: 
  minimum_peak_signal: NULL
  scan_subset: NULL
  ladder_selection_window: 5
  max_combinations: 2500000
  warning_rsq_threshold: 0.998
  show_progress_bar: TRUE

find_fragments:
  smoothing_window: 21
  minimum_peak_signal: 20
  max_bp_size: 1000
  peakpat: '[+]{6,}[0]*[-]{6,}'

find_alleles:
  peak_region_size_gap_threshold: 6
  peak_region_signal_threshold_multiplier: 1
